export const quotes = [
    "Good food is the foundation of genuine happiness.",
    "Food is not just fuel, it's an experience.",
    "Life is uncertain, eat dessert first.",
    "The secret ingredient is always love.",
    "Eat well, live well, be well.",
    "Food is the ingredient that binds us together.",
    "Cooking is love made visible.",
    "Good food, good mood.",
    "Happiness is homemade.",
    "Food is the ultimate pacifier.",
    "Eating is a necessity, but cooking is an art.",
    "First we eat, then we do everything else.",
    "The fondest memories are made gathered around the table.",
    "Food is the most primitive form of comfort.",
    "A recipe has no soul. You, as the cook, must bring soul to the recipe.",
    "Food is a language that everyone speaks.",
    "The only thing I like better than talking about food is eating.",
    "There is no love sincerer than the love of food.",
    "To eat is a necessity, but to eat intelligently is an art.",
    "Food is our common ground, a universal experience.",
    "One cannot think well, love well, sleep well, if one has not dined well.",
    "Cooking is like love. It should be entered into with abandon or not at all.",
    "Eating good food is my favorite thing in the whole world. Nothing is more blissful.",
    "People who love to eat are always the best people.",
    "Good food is all the sweeter when shared with good friends.",
    "Food is the ingredient that makes us come alive.",
    "Eating is one of the greatest pleasures of life.",
    "A balanced diet is a cookie in each hand.",
    "You don’t need a silver fork to eat good food.",
    "Food is not rational. Food is culture, habit, craving and identity.",
    "Great food is like great sex. The more you have, the more you want.",
    "Good food is the key to happiness.",
    "The belly rules the mind.",
    "The best things in life are sweet.",
    "Food is the ultimate symbol of love.",
    "The best memories are made around the table.",
    "A party without cake is just a meeting.",
    "Life is a combination of magic and pasta.",
    "In the end, we are all just food critics.",
    "Good food is all about balance.",
    "Food is the sunshine of life.",
    "Cooking is the ultimate act of love.",
    "A meal without wine is called breakfast.",
    "Eat to live, don't live to eat.",
    "Life is too short for bad food.",
    "Food is fuel for the soul.",
    "Eat, drink, and be merry.",
    "The best meals are the ones we share.",
    "Life is better with good food.",
    "Cooking is my therapy.",
    "Food is the best medicine.",
    "Good food, good friends, good times.",
    "The kitchen is the heart of the home.",
    "Food brings people together.",
    "Eating is an adventure.",
    "Food is a way to the heart.",
    "You are what you eat.",
    "Cooking is an expression of the land where you are and the culture of that place.",
    "Eat well, travel often.",
    "Food is a celebration of life.",
    "Food is love made edible.",
    "Life is short, eat dessert first.",
    "Cooking is a love story.",
    "Food is a journey, not a destination.",
    "Life is a kitchen. Put on your prettiest apron and whip up something incredible.",
    "Food is a global language.",
    "The best things in life are edible.",
    "Food is an art form.",
    "A good meal makes the heart feel good.",
    "Cooking is like painting or writing a song.",
    "Life is what you bake it.",
    "Food is an important part of a balanced diet.",
    "Cooking is an adventure worth taking.",
    "Food is the spice of life.",
    "A good cook is like a sorceress who dispenses happiness.",
    "Food is the universal language of love.",
    "Cooking is the art of adjustment.",
    "Life is a kitchen, and I’m a chef.",
    "Food is the joy of living.",
    "Cooking is the ultimate expression of self-love.",
    "The way to anyone's heart is through their stomach.",
    "Food is a way to connect with the world.",
    "Cooking is like a love affair.",
    "Life is a recipe, make it delicious.",
    "Food is a passion.",
    "Cooking is the art of making do with what you have.",
    "Life is what you cook it.",
    "Food is a journey, not a destination.",
    "Cooking is the ultimate act of self-care.",
    "Food is the poetry of the mouth.",
    "Cooking is a way to nurture the soul.",
    "Life is a banquet, and most poor suckers are starving to death.",
    "Food is a bridge between cultures.",
    "Cooking is a labor of love.",
    "Life is what you make it, so make it delicious.",
    "Food is the essence of life.",
    "Cooking is a dance with the senses.",
    "Life is a feast, eat up.",
    "Food is the foundation of happiness.",
    "Life is a bowl of cherries.",
    "Food is a love affair that never ends.",
    "Cooking is the ultimate form of self-expression.",
    "Life is sweet when you have good food.",
    "Food is a journey of flavors.",
    "Cooking is the art of living.",
    "Life is a plate of spaghetti.",
    "Food is a symphony of flavors.",
    "Cooking is the ultimate act of creativity.",
    "Life is a box of chocolates, you never know what you're gonna get.",
    "Food is the key to happiness.",
    "Cooking is a journey, not a destination.",
    "Life is a recipe, make it a good one.",
    "Food is a story that needs to be told.",
    "Cooking is a way to share love.",
    "Life is a culinary adventure.",
    "Food is a canvas for the imagination.",
    "Cooking is the ultimate form of art.",
    "Life is a gourmet meal.",
    "Food is the soundtrack of life.",
    "Cooking is the ultimate form of expression.",
    "Life is a potluck, and everyone brings something to the table.",
    "Food is the language of love.",
    "Cooking is the ultimate act of giving.",
    "Life is a buffet, and I'm going back for seconds.",
    "Food is a celebration of life.",
    "Cooking is the ultimate act of care.",
    "Life is a recipe, make it delicious.",
    "Food is a journey of the senses.",
    "Cooking is the ultimate act of creativity.",
    "Life is a dish best served with love.",
    "Food is a gift from the heart.",
    "Cooking is a journey of the soul.",
    "Life is a picnic, and I'm bringing the food.",
    "Food is the joy of life.",
    "Cooking is the ultimate form of self-care.",
    "Life is a smorgasbord, and I'm sampling everything.",
    "Food is a labor of love.",
    "Cooking is the ultimate form of expression.",
    "Life is a feast, enjoy every bite.",
    "Food is a way to connect with others.",
    "Cooking is the ultimate form of creativity.",
    "Life is a recipe, make it a good one.",
    "Food is a journey of discovery.",
    "Cooking is the ultimate act of love.",
    "Life is a banquet, and I'm eating it up.",
    "Food is a way to show love.",
    "Cooking is the ultimate form of self-expression.",
    "Life is a potluck, and I'm bringing my best dish.",
    "Food is a celebration of flavors.",
    "Cooking is the ultimate form of art.",
    "Life is a dish best served with love.",
    "Food is a journey of the senses.",
    "Cooking is the ultimate act of creativity.",
    "Life is a feast, and I'm enjoying every bite.",
    "Food is a way to connect with others.",
    "Cooking is the ultimate form of self-care.",
    "Life is a smorgasbord, and I'm sampling everything.",
    "Food is a labor of love.",
    "Cooking is the ultimate form of expression.",
    "Life is a banquet, and I'm eating it up.",
    "Food is a way to show love.",
    "Cooking is the ultimate act of love.",
    "Life is a recipe, make it delicious.",
    "Food is a journey of flavors.",
    "Cooking is the ultimate form of creativity.",
    "Life is a potluck, and I'm bringing my best dish.",
    "Food is a celebration of life.",
    "Cooking is the ultimate act of care.",
    "Life is a dish best served with love.",
    "Food is a journey of discovery.",
    "Cooking is the ultimate act of self-care.",
    "Life is a feast, enjoy every bite.",
    "Food is a way to connect with others.",
    "Cooking is the ultimate form of creativity.",
    "Life is a smorgasbord, and I'm sampling everything.",
    "Food is a labor of love.",
    "Cooking is the ultimate form of expression.",
    "Life is a banquet, and I'm eating it up.",
    "Food is a way to show love.",
    "Cooking is the ultimate act of love.",
    "Pizza is a slice of heaven on earth.",
  "Life is too short to eat bad pizza.",
  "Pizza is always a good idea.",
  "You can't make everyone happy, but you can make pizza.",
  "Pizza is my love language.",
  "A pizza a day keeps the sadness away.",
  "Pizza is not just a food, it's an emotion.",
  "In pizza we crust.",
  "Pizza is the circle of life.",
  "Pizza: because every slice counts.",
  "Pizza makes the world go 'round.",
  "Pizza is happiness in every bite.",
  "The best part of the day is pizza o'clock.",
  "Pizza is the answer, no matter the question.",
  "Love at first slice.",
  "Pizza is the glue that holds us all together.",
  "Keep calm and eat pizza.",
  "Pizza is a little piece of magic.",
  "Pizza is the only love triangle I want.",
  "Pizza: the perfect food for any occasion.",
  "Pizza: the only circle of trust you'll ever need.",
  "All you need is love and pizza.",
  "Pizza is the universal language of love.",
  "Pizza is like the entire food pyramid in one dish.",
  "Life is better with pizza.",
  "Pizza is the secret to happiness.",
  "Pizza: one bite and you're in paradise.",
  "Pizza makes everything better.",
  "Pizza is a slice of joy.",
  "Pizza is my spirit animal.",
  "Pizza: the ultimate comfort food.",
  "Pizza is the way to my heart.",
  "Pizza: a symphony of flavors in every bite.",
  "Pizza is a work of art.",
  "Pizza is the best friend you can eat.",
  "Pizza is the perfect combination of flavors.",
  "Pizza is the ultimate party food.",
  "Pizza is the key to my heart.",
  "Pizza is a slice of perfection.",
  "Pizza: the food that brings people together.",
  "Pizza: the ultimate treat.",
  "Pizza is the best medicine.",
  "Pizza is the reason I wake up every day.",
  "Pizza: because no great story ever started with a salad.",
  "Pizza is the love of my life.",
  "Pizza: the perfect excuse to eat cheese.",
  "Pizza is the king of all foods.",
  "Pizza is my happy place.",
  "Pizza is a slice of pure joy.",
  "Pizza: the food of the gods.",
  "Pizza is the answer to all of life's problems.",
  "Pizza is my kind of therapy.",
  "Pizza: the ultimate mood booster.",
  "Pizza is my soulmate.",
  "Pizza: the only reason I need to smile.",
  "Pizza is the highlight of my day.",
  "Pizza is the best thing since sliced bread.",
  "Pizza: the ultimate love story.",
  "Pizza is the way to my soul.",
  "Pizza: the perfect blend of cheese, sauce, and crust.",
  "Pizza is the ultimate indulgence.",
  "Pizza is the reason for my existence.",
  "Pizza: because life is too short to eat bad food.",
  "Pizza is the ultimate expression of love.",
  "Pizza: the perfect food for any time of day.",
  "Pizza is the ultimate pick-me-up.",
  "Pizza is my one true love.",
  "Pizza: the perfect way to end the day.",
  "Pizza is a slice of happiness.",
  "Pizza: the ultimate comfort food.",
  "Pizza is the food of the gods.",
  "Pizza: the ultimate guilty pleasure.",
  "Pizza is the key to my heart.",
  "Pizza: the perfect combination of flavors.",
  "Pizza is the ultimate food experience.",
  "Pizza is the love of my life.",
  "Pizza: the ultimate treat.",
  "Pizza is the best part of any day.",
  "Pizza: the food that dreams are made of.",
  "Pizza is my reason for living.",
  "Pizza: the perfect way to celebrate life.",
  "Pizza is the ultimate culinary delight.",
  "Pizza is the food of the people.",
  "Pizza: the ultimate party food.",
  "Pizza is the highlight of my week.",
  "Pizza: the perfect way to say 'I love you'.",
  "Pizza is the ultimate comfort food.",
  "Pizza is the food of the gods.",
  "Pizza: the ultimate guilty pleasure.",
  "Pizza is the key to my heart.",
  "Pizza: the perfect combination of flavors.",
  "Pizza is the ultimate food experience.",
  "Pizza is the love of my life.",
  "Pizza: the ultimate treat.",
  "Pizza is the best part of any day.",
  "Pizza: the food that dreams are made of.",
  "Pizza is my reason for living.",
  "Pizza: the perfect way to celebrate life.",
  "Pizza is the ultimate culinary delight.",
  "Pizza is the food of the people.",
  "Butter chicken: the reason I wake up in the morning.",
  "Chole bhature: because who needs a diet anyway?",
  "Paneer tikka: the vegetarian's revenge.",
  "Samosas: little pockets of joy.",
  "Masala dosa: a breakfast fit for a king.",
  "Biryani: the one true love story.",
  "Gulab jamun: sweet dreams are made of this.",
  "Pav bhaji: because bread and butter just won't do.",
  "Pani puri: tiny explosions of flavor.",
  "Rogan josh: because sometimes, curry is the answer.",
  "Tandoori chicken: better than a spa day.",
  "Aloo paratha: carb-loading, Indian style.",
  "Rasgulla: balls of happiness.",
  "Idli: proof that good things come in small packages.",
  "Vada pav: Mumbai's answer to the burger.",
  "Rajma chawal: a hug in a bowl.",
  "Dhokla: fluffy, yellow goodness.",
  "Mutter paneer: the reason peas were invented.",
  "Kheer: a bowlful of sweet nostalgia.",
  "Bhindi masala: making okra great again.",
  "Prawn curry: swimming in flavor.",
  "Mysore pak: the sweet that packs a punch.",
  "Chana masala: chickpeas, but make it spicy.",
  "Malai kofta: a vegetarian's delight.",
  "Poha: breakfast, but make it light.",
  "Pesarattu: the green dosa of dreams.",
  "Chicken 65: a spicy affair.",
  "Baingan bharta: the eggplant's redemption.",
  "Appam: fluffy clouds on a plate.",
  "Papdi chaat: chaos in a bowl.",
  "Fish fry: swimmingly delicious.",
  "Pulao: a rice dish with flair.",
  "Methi thepla: the travel buddy you need.",
  "Pesarattu: green and glorious.",
  "Keema pav: a meaty marvel.",
  "Lassi: drink your dessert.",
  "Pesarattu: the green giant.",
  "Sarson ka saag: leafy love.",
  "Makki ki roti: golden circles of joy.",
  "Sabudana khichdi: tapioca triumph.",
  "Bhatura: puffed up perfection.",
  "Pesarattu: green with envy.",
  "Palak paneer: the ultimate leafy affair.",
  "Kachori: a flaky dream.",
  "Pesarattu: green machine.",
  "Dahi bhalla: yogurt bliss.",
  "Pesarattu: lean, green, and mean.",
  "Dal makhani: buttery goodness.",
  "Pesarattu: healthy and happy.",
  "Paneer bhurji: scrambled perfection.",
  "Pesarattu: green and clean.",
  "Masala chai: India's answer to coffee.",
  "Jalebi: swirls of sweetness.",
  "Pesarattu: the green revolution.",
  "Korma: a royal treat.",
  "Pesarattu: green dream.",
  "Vindaloo: spice up your life.",
  "Pesarattu: the green queen.",
  "Sev puri: crispy chaos.",
  "Pesarattu: leafy green love.",
  "Butter naan: the softest sidekick.",
  "Pesarattu: the green delight.",
  "Raita: yogurt with a twist.",
  "Pesarattu: green and keen.",
  "Kulfi: the Indian ice cream.",
  "Pesarattu: green and lean.",
  "Sambar: soupy goodness.",
  "Pesarattu: green and serene.",
  "Upma: savory comfort.",
  "Pesarattu: the green scene.",
  "Shahi tukda: bread royal.",
  "Pesarattu: green and clean.",
  "Kadhi: creamy and dreamy.",
  "Pesarattu: the green machine.",
  "Misal pav: spicy symphony.",
  "Pesarattu: the green team.",
  "Aloo gobi: potatoes and cauliflower unite.",
  "Pesarattu: the green supreme.",
  "Pesarattu: the green extreme.",
  "Pesarattu: green cuisine.",
  "Pesarattu: a green routine.",
  "Pesarattu: green and mean.",
  "Pesarattu: green cuisine.",
  "Pesarattu: green and serene.",
  "Pesarattu: green supreme.",
  "Pesarattu: green machine.",
  "Pesarattu: green dream.",
  "Pesarattu: green queen.",
  "Pesarattu: green scene.",
  "Pesarattu: green keen.",
  "Pesarattu: green serene.",
  "Pesarattu: green routine.",
  "Pesarattu: green cuisine.",
  "Pesarattu: green mean.",
  "Pesarattu: green team.",
  "Pesarattu: green supreme.",
  "Pesarattu: green dream."
];
  